services:
  # The Ollama AI Engine
  ollama:
    image: richardjoseph1/ollama-kube-openwebui:latest
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    networks:
      - app-network

  # The Go Backend Service
  backend:
    container_name: modelmanager-backend
    image: richardjoseph1/modelmanager-backend-kube-openwebui:latest
    environment:
      - OLLAMA_HOST=http://ollama:11434
    depends_on:
      - ollama
    networks:
      - app-network

  # Your custom Vue.js Frontend Service
  frontend:
    container_name: modelmanager-frontend
    image: richardjoseph1/modelmanager-frontend-kube-openwebui:latest
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - app-network

  # The OpenWebUI Service 
  open-webui:
    image: richardjoseph1/open-webui-kube-openwebui:latest
    container_name: open-webui
    ports:
      - "8080:8080"
    environment:
      - 'OLLAMA_BASE_URL=http://ollama:11434'
    volumes:
      - open_webui_data:/app/backend/data
    depends_on:
      - ollama
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  ollama_data:
  open_webui_data:
