# 00-persistent-volumes.yml
apiVersion: v1
kind: PersistentVolume
metadata:
  name: ollama-pv
spec:
  capacity:
    storage: 5Gi # Matches the request in the ollama StatefulSet
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/ollama" # IMPORTANT: Create this directory on your node