apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: modelmanager-backend
        # CHANGED: Replaced ':latest' with a stable placeholder for the CI/CD pipeline.
        image: richardjoseph1/modelmanager-backend-kube-openwebui:c91126c3f306bd21bcf1c4c5bec7358de6de310b
        
        ports:
        - containerPort: 8080
        env:
        - name: OLLAMA_HOST
          value: "http://ollama:11434"
        resources:
          requests:
            cpu: "20m"
            memory: "256Mi"
          limits:
            cpu: "50m"
            memory: "512Mi"
        livenessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /api/models
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10