# 03-open-webui.yml
apiVersion: v1
kind: Service
metadata:
  name: open-webui
spec:
  type: NodePort # Exposes the service on each Node's IP at a static port.
  selector:
    app: open-webui
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30080 # Access via http://<your-node-ip>:30080
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: open-webui
spec:
  serviceName: "open-webui"
  replicas: 1
  selector:
    matchLabels:
      app: open-webui
  template:
    metadata:
      labels:
        app: open-webui
    spec:
      volumes: # Define the volume and link it to our PVC
      - name: open-webui-data
        persistentVolumeClaim:
          claimName: open-webui-data-pvc
      containers:
      - name: open-webui
        image: richardjoseph1/open-webui-kube-openwebui:latest
        ports:
        - containerPort: 8080
        env:
        - name: OLLAMA_BASE_URL
          value: "http://ollama:11434" # Connects to the ollama service
        volumeMounts: # Mount the volume defined above
        - name: open-webui-data
          mountPath: /app/backend/data