# 03-open-webui.yml
apiVersion: v1
kind: Service
metadata:
  name: open-webui
spec:
  type: NodePort
  selector:
    app: open-webui
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: open-webui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: open-webui
  template:
    metadata:
      labels:
        app: open-webui
    spec:
      volumes:
        - name: open-webui-data-volume
          persistentVolumeClaim:
            claimName: open-webui-data-pvc
      containers:
      - name: open-webui
        image: ghcr.io/open-webui/open-webui:main 
        ports:
        - containerPort: 8080
        env:
        - name: OLLAMA_BASE_URL
          value: "http://ollama:11434"
        volumeMounts:
        - name: open-webui-data-volume
          mountPath: /app/backend/data
        resources:
          requests:
            cpu: "250m"
            memory: "512Mi"