# 07-network-policies.yml

# 1. Default Deny (Unchanged)
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default-deny-all
spec:
  podSelector: {}
  policyTypes:
  - Ingress
  - Egress
---
# 2. 'ollama' policy (Unchanged)
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: ollama-policy
spec:
  podSelector:
    matchLabels:
      app: ollama
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: openwebui
    - podSelector:
        matchLabels:
          app: backend
  egress:
  - to:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: kube-system
      podSelector:
        matchLabels:
          k8s-app: kube-dns
    ports:
    - protocol: UDP
      port: 53
    - protocol: TCP
      port: 53
---
# 3. 'backend' policy (Unchanged)
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: backend-policy
spec:
  podSelector:
    matchLabels:
      app: backend
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: frontend
  egress:
  - to:
    - podSelector:
        matchLabels:
          app: ollama
  - to:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: kube-system
      podSelector:
        matchLabels:
          k8s-app: kube-dns
    ports:
    - protocol: UDP
      port: 53
    - protocol: TCP
      port: 53
---
# 4. MODIFIED 'frontend' specific policy
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: frontend-policy
spec:
  podSelector:
    matchLabels:
      app: frontend
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - {}
  egress:
  - to:
    - podSelector:
        matchLabels:
          app: backend
  # THIS IS THE FIX: A more reliable rule to allow DNS lookups.
  - to:
    - namespaceSelector:
        matchLabels:
          # This selects the kube-system namespace where DNS pods live
          kubernetes.io/metadata.name: kube-system
      podSelector:
        matchLabels:
          k8s-app: kube-dns
    ports:
    # Allow both UDP and TCP for DNS
    - protocol: UDP
      port: 53
    - protocol: TCP
      port: 53
---
# 5. MODIFIED 'openwebui' specific policy
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: openwebui-policy
spec:
  podSelector:
    matchLabels:
      app: openwebui
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - {}
  egress:
  - to:
    - podSelector:
        matchLabels:
          app: ollama
  # THIS IS THE FIX: A more reliable rule to allow DNS lookups.
  - to:
    - namespaceSelector:
        matchLabels:
          kubernetes.ioio/metadata.name: kube-system
      podSelector:
        matchLabels:
          k8s-app: kube-dns
    ports:
    # Allow both UDP and TCP for DNS
    - protocol: UDP
      port: 53
    - protocol: TCP
      port: 53