# This is the name of the consolidated workflow.
name: CI & CD Pipeline

# Triggers the workflow on push or pull request events but only for the "main" branch.
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  # JOB 1: Lints the code, runs unit tests, and verifies the application builds successfully.
  lint-build-and-test:
    name: Lint, Build & Test
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.22' # Corresponds to the go.mod file
        cache: true

    - name: Lint code
      uses: golangci/golangci-lint-action@v6
      continue-on-error: true
      with:
        # Optional: version of golangci-lint to use in form of v1.2.3 or `latest` to use the latest version
        version: latest

    - name: Build application
      run: go build -v ./...

    - name: Run unit tests
      run: go test -v ./tests/...

  # JOB 2: Runs security scans for vulnerable dependencies (SCA) and secrets.
  security-scans:
    name: Security Scans (SCA & SAST)
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.22'

    - name: Software Component Analysis (SCA)
      run: |
        go install golang.org/x/vuln/cmd/govulncheck@latest
        govulncheck ./... || true

    - name: Static Application Security Testing (SAST) with Gitleaks
      uses: gitleaks/gitleaks-action@v2
      continue-on-error: true
      with:
        # Gitleaks configuration is managed in the .pre-commit-config.yaml
        config-path: .pre-commit-config.yaml

  # JOB 3: Performs in-depth static analysis with CodeQL.
  codeql-analysis:
    name: CodeQL Analysis
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      packages: read
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Initialize CodeQL
      uses: github/codeql-action/init@v3
      with:
        languages: go # Specific language for analysis

    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v3
      continue-on-error: true
      with:
        category: "/language:go"

  # JOB 4: Builds and pushes the Docker image and updates the Kubernetes manifest.
  # This job will ONLY run after the three CI jobs above succeed, and only on a push to main.
  build-push-and-update-manifest:
    name: Build, Push & Update Manifest
    runs-on: ubuntu-latest
    
    # Define dependencies: This job waits for the CI jobs to be successful.
    needs: [lint-build-and-test, security-scans, codeql-analysis]
    
    # Define condition: This job only runs for push events on the main branch.
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    # Add permissions to allow the job to commit back to the repository.
    permissions:
      contents: write
      
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: richardjoseph1
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile
        push: true
        # CHANGED: Tag the image with the short commit SHA instead of 'latest'.
        tags: richardjoseph1/modelmanager-backend-kube-openwebui:${{ github.sha }}

    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: 'richardjoseph1/modelmanager-backend-kube-openwebui:${{ github.sha }}'
        format: 'table'
        exit-code: '1'
        ignore-unfixed: true
        vuln-type: 'os,library'
        severity: 'CRITICAL,HIGH'

    - name: Update deployment manifest
      # ADDED: This step updates the image tag in your deployment file.
      # Assumes your file is located at 'kubernetes/deployment.yaml'.
      run: |
        sed -i "s|image: .*|image: richardjoseph1/modelmanager-backend-kube-openwebui:${{ github.sha }}|g" kubernetes/02-backend-deployment.yml

    - name: Commit and push manifest changes
      # ADDED: This step commits the updated manifest file back to your main branch.
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add kubernetes/02-backend-deployment.yml
        git diff --staged --quiet || git commit -m "CI: Update image tag to ${{ github.sha }}"
        git push