# A more descriptive name for the workflow
name: CI, Security Scans, and Deployment

# Triggers the workflow on push or pull request events to the "main" branch
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

# Environment variables for reusability
env:
  REGISTRY: docker.io
  IMAGE_NAME: richardjoseph1/modelmanager-frontend-kube-openwebui

jobs:
  # JOB 1: Consolidated CI checks for linting, building, and basic security scans.
  # This reduces redundancy by running setup steps only once.
  ci-checks:
    name: Lint, Build & Security Scans
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Lint code
        run: npm run lint

      - name: Build application
        run: npm run build

      - name: Software Component Analysis (SCA)
        run: npm audit --audit-level=high

      - name: Scan for leaked secrets
        uses: gitleaks/gitleaks-action@v2
        with:
          config-path: .gitleaks.toml

  # JOB 2: Performs in-depth static analysis with CodeQL.
  # Kept as a separate job due to its specific setup and permissions.
  codeql-analysis:
    name: CodeQL Analysis
    runs-on: ubuntu-latest
    continue-on-error: true
    permissions:
      security-events: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: javascript-typescript

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3
        with:
          category: "/language:javascript-typescript"

  # JOB 3: Builds, pushes Docker image, and updates manifest using the Git SHA.
  build-and-deploy:
    name: Build, Push & Deploy
    runs-on: ubuntu-latest
    needs: [ci-checks, codeql-analysis]
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # STEP REMOVED: The 'Extract Docker metadata' action is no longer needed.
      
      # CHANGED: The 'tags' field now directly uses the built-in github.short_sha variable.
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ env.IMAGE_NAME }}:${{ github.short_sha }}

      # CHANGED: The sed command also uses github.short_sha to ensure consistency.
      - name: Update deployment manifest
        run: |
          sed -i "s|image: .*|image: ${{ env.IMAGE_NAME }}:${{ github.short_sha }}|g" kubernetes/deployment.yaml

      # CHANGED: The commit message now references the short SHA directly.
      - name: Commit and push manifest changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add kubernetes/deployment.yaml
          git diff --staged --quiet || git commit -m "CI: Update image tag to ${{ github.short_sha }}"
          git push