name: 'Code Coverage Report'

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  code-coverage-report:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'
          cache: true

      - name: Run tests with coverage
        run: go test -v -coverprofile=coverage.out ./tests/...

      - name: Post coverage report to PR
        uses: Misha-K-S/go-coverage-report@v1.5.0
        with:
          coverage-file: coverage.out
          github-token: ${{ secrets.GITHUB_TOKEN }}