name: 'Code Coverage Report'

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  code-coverage-report:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'
          cache: true

      - name: Run tests with coverage
        run: go test -v -coverprofile=coverage.out ./tests/...

      - name: Generate coverage summary
        id: coverage
        run: echo "report=$(go tool cover -func=coverage.out)" >> $GITHUB_OUTPUT

      - name: Post coverage report to PR
        uses: actions/github-script@v6
        with:
          script: |
            const output = `## Code Coverage Report
            \`\`\`
            ${{ steps.coverage.outputs.report }}
            \`\`\`
            `;
            github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: output
            })